# Generated by Django 2.0.6 on 2019-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchainuser',
            name='nonce',
            field=models.CharField(default='sdgfd485dfhb54gfn45cgfm455', max_length=70, unique=True),
        ),
    ]
