# Generated by Django 2.0.6 on 2019-09-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_docchainuser_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docchainuser',
            name='nonce',
        ),
    ]
