# Generated by Django 2.0.6 on 2019-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_docchainuser_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchainuser',
            name='nonce',
            field=models.CharField(default=1, max_length=10, unique=True),
        ),
    ]
