# Generated by Django 2.0.6 on 2019-09-13 13:56

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190913_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docchainuser',
            name='nonce',
            field=models.CharField(default=profiles.models.DocchainUser.defaultValue, max_length=20, unique=True),
        ),
    ]
